version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .production.env
    ports:
      - 5555:5555
    command: npm run start:prod
    depends_on:
      db:
        condition: service_started
    restart: always
  db:
    container_name: db
    image: postgres:13
    env_file:
      - .production.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    restart: always

volumes:
  pgdata: